### ISSUE TITLE
traduction en francais / translate in french

### ISSUE THREAD

**Issue by freeshare** [Nathan1258/Menubar-Weather#10]
Hello
Bravo for this work, bravo for this application
Attached is the file with the French translations, if you want to include them in a future release.

[Localizable.xcstrings.txt](https://github.com/user-attachments/files/15748790/Localizable.xcstrings.txt)

**Comment by Nathan1258** [comment]
Hello, @freeshare

Sorry for the late reply, and I thank you for this, I'll find some time next week to implement it :)

**Comment by Nathan1258** [comment]
French will be added to the new version coming in the next update :)
