### ISSUE TITLE
Feature requests - Possibility to add location manualy

### ISSUE THREAD

**Issue by Exadith** [Nathan1258/Menubar-Weather#11]
Request to add the ability to enter locations manually. 
On Mac Mini if u use internet lan connection and have disable wifi connection then MacOs cant get correct location.

**Comment by Nathan1258** [comment]
Hi @Exadith 

Can you just confirm that you're reporting an issue where the app can't get your location when on LAN?

**Comment by Exadith** [comment]
exactly

**Comment by Nathan1258** [comment]
@Exadith I'll take a look!

**Comment by Nathan1258** [comment]
> exactly

Hi @Exadith Please could you provide the following:

- Any error messages given by the app (i.e. does it tell you when the app is offline or does it just say "We're fetching your weather" indefinitely?)
- What app version are you using?
- If possible, please provide a screenshot of the app when this behaviour occurs.

Thank you!

**Comment by Exadith** [comment]
Hi @Nathan1258,

- Any error messages given by the app (i.e. does it tell you when the app is offline or does it just say "We're fetching your weather" indefinitely?)
App shows window with information -> " We're fetching your weather " and try get data but with no success.

- What app version are you using?
1.3.4
- If possible, please provide a screenshot of the app when this behaviour occurs.
I will send screenshot later 


I once read about getting location via MacOs. MacOs uses a WIFI connection to retrieve the location. If WIFI is turned off, unfortunately MacOs cannot get the location. So if it was possible to alternatively provide the location, e.g. by city name or geographical coordinates, it would solve the problem of users using a LAN connection.

**Comment by Nathan1258** [comment]
Hi @Exadith,

Yes, that was what I was thinking. One workaround would be to keep your Wi-Fi connection on (you do not have to connect to any Wi-Fi network, just keep the setting on), and still use ethernet to connect to internet, your Mac will use ethernet as usual, but will use the Wi-Fi for location-based stuff (i.e. this app).

I'm looking at the possibility to add manual locations, however I'm limited to 500k (free) API calls/month and allowing users to manually add locations gives the user the potential to abuse this. As it stands I've used 80% of API calls this month and it resets in 13 days time. I'd like to keep the app free, however this may have to change in the near future if people are wanting these features. Let me know your thoughts!

**Comment by Exadith** [comment]
Is there any free provider of weather with no limitation?

**Comment by Nathan1258** [comment]
@Exadith 

Not really, no. No API is free - and if it is then you pay using data and other means. I chose WeatherKit due to its privacy and it being built-in with macOS. It has its moments, but it is pretty accurate too. I'm looking into the possibility of allowing the user to choose between a selection of weather providers and using their own API key if they want to do things such as manually adding a location.

**Comment by Exadith** [comment]
First service that i found -> https://open-meteo.com/ but u will propably know it.

**Comment by Nathan1258** [comment]
@Exadith,

Yes, I've seen that - it costs and is limited to only 10K calls. Could be a potential provider if I implement allowing users to add their own weather providers.

I'm going to close this issue as sadly Mac's do not have GPS chips and do need Wi-Fi to work. I could go down the route of using a user's IP address but then that would go against the privacy aspect I wanted this app to have. I will continue to find other solutions.
