### ISSUE TITLE
Feature request: Open the app using a keyboard shortcut

### ISSUE THREAD

**Issue by RStelzle** [Nathan1258/Menubar-Weather#12]
Hi Nathan,

what a great little app! I just wondered wether it would be possible to add a setting allowing users to specify a keyboard shortcut that opens up (and closes I guess) the app from the menu bar?

Best wishes,
Robert

**Comment by Nathan1258** [comment]
Hey @RStelzle,

Thank you! I like that idea and will take a look at it after I've implemented the most asked feature: setting manual multiple locations. :)

**Comment by Nathan1258** [comment]
Hey @RStelzle,

I have just added this feature to the upcoming update on the App Store. If you're using the free version of the app (the one downloaded from this Git repo), then this feature will be coming soon as I have to fix the app signing issues when using third-party packages.

**Comment by RStelzle** [comment]
Very cool, looking forward to checking it out in the coming days!
