### ISSUE TITLE
Settings / Quit Buttons Text is badly styled

### ISSUE THREAD

**Issue by davisstu** [Nathan1258/Menubar-Weather#13]
The text on the Settings and Quit button are badkly styled, regularly displaying dark text on dark backgrounds. For example:

![image](https://github.com/Nathan1258/Menubar-Weather/assets/8912521/14f91e9d-fe00-47ff-9ff1-aae87d61d7a9)

I know that the BG is dynamic based on the current weather but this doesn't help it's aesthetics or it's accessibility.

Thanks

**Comment by Nathan1258** [comment]
@davisstu 

Thanks for brining to my attention! I shall fix this ASAP.

**Comment by davisstu** [comment]
Resolved in latest release.
