### ISSUE TITLE
The Settings/Quit buttons a restyle buggy

### ISSUE THREAD

**Issue by fnsign** [Nathan1258/Menubar-Weather#19]
In the latest release the Settings and Quit buttons shall be fixed,(#13) but there is still a bug. They are not legible.
![Screenshot 2024-07-17 at 21 45 07](https://github.com/user-attachments/assets/85b6b580-c8ed-4dc5-b6a3-db625ded60db)

**Comment by Nathan1258** [comment]
Hi @fnsign, 

I've pushed an update to both the App Store and GitHub version to fix this issue. The app is currently building and will be available later today. Thanks for reporting this!
