### ISSUE TITLE
Time on the hourly is cut off

### ISSUE THREAD

**Issue by ttyler1999** [Nathan1258/Menubar-Weather#2]
<img width="479" alt="Screenshot 2024-05-23 at 11 11 05 AM" src="https://github.com/Nathan1258/Menubar-Weather/assets/4110816/911bd23c-7d0e-4389-a875-9ae394f756ab">

The time on the hourly is cut off near the top.

**Comment by Nathan1258** [comment]
@ttyler1999 thanks for outlining this issue, I have fixed the issue and the update will be live as soon as it has even reviewed by Apple

**Comment by ttyler1999** [comment]
Awesome, thanks, keep up the great work. Your free app is wonderful!

**Comment by ttyler1999** [comment]
Wow, that was really quick!
<img width="397" alt="Screenshot 2024-05-23 at 3 26 18 PM" src="https://github.com/Nathan1258/Menubar-Weather/assets/4110816/fc1e4470-3e54-4abf-a125-368fd751faa7">
