### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by Svec-Tomas** [Nathan1258/Menubar-Weather#3]
Hi Nathan,

I am not familiar with Pull requests, so please find attached the Slovak translation here.
[Localizable.xcstrings.zip](https://github.com/Nathan1258/Menubar-Weather/files/15420953/Localizable.xcstrings.zip)

If there is anything else needed, please let me know.

I did not find some strings for translation, so maybe I have not used the latest file?

Also I guess App Store description would be great to have translated together with the images.

I would personally also translate the app name MenuBar Weather - Počasie v lište This would help to find the app for Slovak users the app easier in the App Store. But this is of course your decision.

**Comment by Nathan1258** [comment]
@Svec-Tomas Thank you for your time! I will implement the translation for Slovak on the next update for the app. I will try to complete any strings you may have missed and contact you if I need any more help. 

I will get around for translating the App Store page (and the app's name) however, there are some other features that need more attention first.

**Comment by Nathan1258** [comment]
Done! Thanks for the translation again
