### ISSUE TITLE
"Today" not translated

### ISSUE THREAD

**Issue by jotka** [Nathan1258/Menubar-Weather#5]
I've noticed the "Today" string is not translated:

<img width="804" alt="image" src="https://github.com/Nathan1258/Menubar-Weather/assets/2701356/c17bd5ae-8575-4ae2-b328-1fafa091a993">

**Comment by Nathan1258** [comment]
@jotka Hi, that's odd - I'll take a look I notice 'Now' isn't translated either?

**Comment by Nathan1258** [comment]
@jotka Issue has been fixed, will roll out update soon :)
