### ISSUE TITLE
"Go to GitHub Page" not translated

### ISSUE THREAD

**Issue by Svec-Tomas** [Nathan1258/Menubar-Weather#6]
![MenuBar Weather Go to GitHub Page](https://github.com/Nathan1258/Menubar-Weather/assets/138758322/776835c0-16b7-49b2-922e-52915150086b)

Hi Nathan, as you can see on the attached screenshot, in the Settings the button is still in English.

In Slovak it will be then: Prejsť na GitHub stránku

**Comment by Nathan1258** [comment]
@Svec-Tomas hi, this issue is fixed in the newest update that is currently in review by Apple 😃
