### ISSUE TITLE
[FR]: Open Weather App when clicking on pane.

### ISSUE THREAD

**Issue by fnsign** [Nathan1258/Menubar-Weather#7]
Hi,

stumbled over that lovely app on reddit and I totally love it!
I had a small feature request:
I would like to open the Mac weather map, when I click on the weather pane, just like with the original weather widget. That way I could quickly see weather details (e.g. hourly precipitation forecast).
Would that be possible?

**Comment by Nathan1258** [comment]
Hi @fnsign,

I have implemented this feature and will be in the next update. You can tap on the weather icon in the top right and it will open the weather app for you (if installed of course).

**Comment by fnsign** [comment]
Great, thanks a lot!
